server:
  port: 7083
  servlet:
    context-path: /
eureka:
  instance:
    hostname: eureka3
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka1:7081,http://eureka2:7082
